name: Docker

on:
  workflow_call:


jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DCKR_USER }}
        password: ${{ secrets.DCKR_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: '.'
        file: './Dockerfile'
        push: true
        tags: '${{ secrets.DCKR_USER }}/alura-github-actions:${{ github.ref_name }}'
