name: EC2 Continuous Delivery

on:
  workflow_call:


jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: 'artifact'
        path: '.'

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: '/home/${{ secrets.EC2_USER }}'
        EXCLUDE: './postgres-data'

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export HOST=${{ secrets.DB_HOST }}
          export USER=${{ secrets.DB_USER }}
          export PASSWORD=${{ secrets.DB_PASSWORD }}
          export DBNAME=${{ secrets.DB_NAME }}
          export DBPORT=${{ secrets.DB_PORT }}
          export PORT=8000
          chmod +x main
          nohup ./main > nohup.out 2> nohup.err < /dev/null &